- .travis.yml
- composer.json
This PR adds a check in for the lowest package dependencies.
It also fixes the lowest dependencies.
> [Travis] test lowest dependencies

- .travis.yml
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
- composer.json
also tweaked some aspects of the travis configuration and the composer requires
> enabled Symfony 3.0 support

- .scrutinizer.yml
- .travis.yml
- README.md
- composer.json
- phpunit.xml.dist
- added status badges
- removed php 5.4 tests (since jms/serializer does not support php 5.4 anymore)
- using local phpunit (not the one installed on travis)
- fixed whitelist for modern phpunit
anybody wants to have a look?
> Improve build info and CI

- Resources/config/services.xml
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
- composer.json
Added support for context factories introduced with serializer [v1.4.0](https://github.com/schmittjoh/serializer/releases/tag/1.4.0)
> Context factories

- DependencyInjection/Configuration.php
- DependencyInjection/JMSSerializerExtension.php
- ExpressionLanguage/BasicSerializerFunctionsProvider.php
- Resources/config/services.xml
- Resources/doc/configuration.rst
- Tests/DependencyInjection/Fixture/ObjectUsingExpressionLanguage.php
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
- composer.json
Added expression language support that will be introduced with serializer [v1.5.0](https://github.com/schmittjoh/serializer/releases/tag/1.5.0-RC1)
> Added expression language support

- DependencyInjection/JMSSerializerExtension.php
- Tests/DependencyInjection/ConfigurationTest.php
https://github.com/schmittjoh/JMSSerializerBundle/pull/524 with tests
Closes https://github.com/schmittjoh/JMSSerializerBundle/pull/524
> Fix metadata directories loading where path is just a bundle name

- DependencyInjection/Compiler/RegisterEventListenersAndSubscribersPass.php
- Tests/DependencyInjection/EventSubscribersAndListenersPassTest.php
- Tests/DependencyInjection/Fixture/EventSubscriber.php
https://github.com/schmittjoh/JMSSerializerBundle/pull/476 with tests 
Closes https://github.com/schmittjoh/JMSSerializerBundle/pull/476
> Allow service parameters in listener class name

- ExpressionLanguage/BasicSerializerFunctionsProvider.php
- Tests/ExpressionLanguage/ExpressionLanguageTest.php
(and fixed minor bug with the is_granted function)
> Expression language tests

- DependencyInjection/JMSSerializerExtension.php
- Resources/config/services.xml
- Tests/DependencyInjection/Fixture/ObjectUsingExpressionProperties.php
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
- composer.json
added support for https://github.com/schmittjoh/serializer/pull/708
to be released with jms serializer v1.6
> Expression language based virtual properties

- README.md
> Use svg build badge

- DependencyInjection/Configuration.php
- DependencyInjection/JMSSerializerExtension.php
- Resources/config/services.xml
- Resources/doc/configuration.rst
- Tests/DependencyInjection/ConfigurationTest.php
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
Added configuration options for recent doctrine improvements on the serializer library
Closes https://github.com/schmittjoh/JMSSerializerBundle/issues/565
Closes https://github.com/schmittjoh/JMSSerializerBundle/issues/539
> Added configuration options for recent doctrine improvements

- .travis.yml
see https://github.com/schmittjoh/JMSSerializerBundle/pull/576#issuecomment-311022923
> install stable dependencies when possible

- .travis.yml
- composer.json
Solve the issues expressed in https://github.com/schmittjoh/JMSSerializerBundle/pull/588#issuecomment-311136094
> Change min stability

- Tests/DependencyInjection/EventSubscribersAndListenersPassTest.php
In order to avoid risky tests [1](https://travis-ci.org/schmittjoh/JMSSerializerBundle/jobs/254914923#L546), [2](https://travis-ci.org/schmittjoh/JMSSerializerBundle/jobs/254914923#L549)
> Added assertions to private services tests

- DependencyInjection/Compiler/CustomHandlersPass.php
- Tests/DependencyInjection/CustomHandlerPassTest.php
Fixes https://github.com/schmittjoh/JMSSerializerBundle/issues/598
> Allow subscribing handlers to be private

- .travis.yml
- DependencyInjection/JMSSerializerExtension.php
- Resources/config/services.xml
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
- composer.json
Will be kept open till the Symfony 4.0 release
> Full Symfony 4 compatibility

- DependencyInjection/JMSSerializerExtension.php
> Extension > Remove stopwatch subscriber when Stopwatch class is not found

- DependencyInjection/JMSSerializerExtension.php
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
This is the continuation of #612 from @blaugueux
> Add autoconfigure feature for sf => 3.3

- DependencyInjection/Compiler/CustomHandlersPass.php
- Tests/DependencyInjection/CustomHandlerPassTest.php
Alternative implementation of https://github.com/schmittjoh/JMSSerializerBundle/pull/657
Fixes https://github.com/schmittjoh/JMSSerializerBundle/issues/656
[Here](https://github.com/schmittjoh/JMSSerializerBundle/compare/2.3.0...discordier-hotfix/issue-656#diff-f7e0c2c60aeb6de7c77b4fa0c978c373L32) there is a better diff with the changes compare to v2.3.0
> Fix serialization handler registration by priority

- Resources/doc/configuration.rst
Hi!
Today as I was working on a ticket for a project at work, I struggled a bit with configuration issues until I found about the issue #601.
That helped, but as it hasn't been fixed yet, decided to contribute back by fixing the docs. Alas, I can't find how to build the web site to look at the change locally.
So I compared the other existing blocks that were working, trying to match the formatting.
Could someone please take a look and see if this fix looks OK when built? Or if someone could point me at how to build the website, I'd be happy to have a look first before asking others to review.
Thanks for such a great library!
Bruno
> Fix Constructors configuration section

- DependencyInjection/Configuration.php
> fix compatibility with Symfony Config 4.2

- Resources/config/services.xml
- composer.json
Adds support for this https://github.com/schmittjoh/serializer/pull/1034
> Iterator handler

- DependencyInjection/Compiler/TwigExtensionPass.php
> Fix deprecation with Twig 2.7

- DependencyInjection/Compiler/TwigExtensionPass.php
The PR fixes #730 for 2.x branch
> Fix deprecation with Twig 2.7 (2.x branch)

- DependencyInjection/Configuration.php
- DependencyInjection/JMSSerializerExtension.php
- Resources/doc/configuration.rst
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
- composer.json
Bundle support following https://github.com/schmittjoh/serializer/pull/1068
> Xml deserialization options

- DependencyInjection/Configuration.php
- Tests/DependencyInjection/ConfigurationTest.php
> Fix jms_serializer.json_serialization_visitor default options

- DependencyInjection/JMSSerializerExtension.php
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
fixes https://github.com/schmittjoh/JMSSerializerBundle/issues/781
> [defaultContext] update ContextFactoryInterface aliases

- Resources/doc/configuration.rst
Related to https://github.com/symfony/symfony/pull/28810
> Symfony 5 parameter doc fix

- .travis.yml
- DependencyInjection/JMSSerializerExtension.php
- Resources/config/services.xml
- Tests/DependencyInjection/Fixture/TypedObject.php
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
- composer.json
- phpunit.xml.dist
adds support for https://github.com/schmittjoh/serializer/pull/1192
> Add support for PHP 7.4 typed properties 

- DependencyInjection/Compiler/TwigExtensionPass.php
- DependencyInjection/JMSSerializerExtension.php
- Tests/DependencyInjection/TwigExtensionPassTest.php
Closes https://github.com/schmittjoh/JMSSerializerBundle/issues/799
> Conditional loading of templating and twig extensions

- .github/CONDUCT.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
> copy issue templates from schmittjoh/serializer

- Cache/CacheWarmer.php
See https://github.com/schmittjoh/JMSSerializerBundle/pull/820/files
This PR partially revert above PR and it is first step for adding support for enum introduced in PHP 8.1.
> Partially revert #820 for support PHP 8.1 Enum

- Cache/CacheClearer.php
- Tests/Cache/CacheClearerTest.php
| Tests pass?   | YES
| Fixed tickets | #... 
> rewrite CacheClearerTest according to --prefer-lowest tests

- DependencyInjection/Compiler/ExpressionFunctionProviderPass.php
- ExpressionLanguage/BasicSerializerFunctionsProvider.php
- Tests/ExpressionLanguage/ExpressionLanguageTest.php
| Fixed tickets | https://github.com/schmittjoh/JMSSerializerBundle/issues/854
> Use public alias for security.authorization_checker service

- DependencyInjection/JMSSerializerExtension.php
- Tests/DependencyInjection/ConfigurationTest.php
- Tests/DependencyInjection/Fixture/IncludeInterfaces/AnInterface.php
- Tests/DependencyInjection/Fixture/IncludeInterfaces/AnInterfaceImplementation.php
- Tests/DependencyInjection/Fixture/IncludeInterfaces/AnObject.php
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
> Add support for php8 attributes

- Debug/TraceableDriver.php
| New feature?  |no
| Doc updated   |no
| BC breaks?    |no 
| Deprecations? |no 
> Fix undefined variable $metadata

- composer.json
| Fixed tickets | https://github.com/schmittjoh/JMSSerializerBundle/issues/882
> require symfony di 3.4+

- DependencyInjection/Configuration.php
- Tests/DependencyInjection/ConfigurationTest.php
| Doc updated   | /no
| Fixed tickets | #890 
> Fix default profiler value

- DependencyInjection/Configuration.php
- DependencyInjection/JMSSerializerExtension.php
- Resources/config/services.xml
- Resources/doc/configuration.rst
- Tests/DependencyInjection/ConfigurationTest.php
- composer.json
| Doc updated   | yes
Companion PR to https://github.com/schmittjoh/serializer/pull/1391
> Add support for the `SymfonyUidHandler`

- Resources/doc/configuration.rst
| Doc updated   | yes
| Tests pass?   | 
| Fixed tickets | 
> Improve configuration docs

- Resources/config/debug.xml
| New feature?  |no
| Fixed tickets | -
> save deserialzer info as well

- Resources/config/services.xml
| Deprecations? |no 
| Fixed tickets | #911 
> Restore removed twig.runtime tag

- Debug/TraceableMetadataFactory.php
https://github.com/schmittjoh/JMSSerializerBundle/issues/907
| Deprecations? | yes
| Fixed tickets | #907
> Fix deprecation in TraceableMetadataFactory

- Resources/views/Collector/panel.html.twig
| Fixed tickets | -
Just a small typo fix :)
> Fix typo in debugger panel

- .github/workflows/ci.yaml
| Fixed tickets | 
Run tests also on PHP8.2
> Run tests on PHP 8.2

- DependencyInjection/JMSSerializerExtension.php
- Tests/DependencyInjection/Fixture/ObjectUsingEnumDeserialize.php
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
| Fixed tickets | https://github.com/schmittjoh/serializer/pull/1458 https://github.com/schmittjoh/serializer/pull/1463 https://github.com/schmittjoh/serializer/issues/1461 https://github.com/schmittjoh/serializer/issues/1457 https://github.com/schmittjoh/JMSSerializerBundle/issues/918
> allow de serialization of enums

- DependencyInjection/JMSSerializerExtension.php
- Resources/config/services.xml
- Tests/DependencyInjection/Fixture/AnotherSimpleObject.php
- Tests/DependencyInjection/Fixture/IncludeInterfaces/AnInterface.php
- Tests/DependencyInjection/Fixture/IncludeInterfaces/AnInterfaceImplementation.php
- Tests/DependencyInjection/Fixture/IncludeInterfaces/AnObject.php
- Tests/DependencyInjection/Fixture/ObjectUsingEnumDeserialize.php
- Tests/DependencyInjection/Fixture/ObjectUsingExpressionLanguage.php
- Tests/DependencyInjection/Fixture/ObjectUsingExpressionProperties.php
- Tests/DependencyInjection/Fixture/SimpleObject.php
- Tests/DependencyInjection/Fixture/VersionedObject.php
Adds support for https://github.com/schmittjoh/serializer/pull/1469
> Add support for the new AttributeDriver

- JMSSerializerBundle.php
> fix(symfony): Fix deprecations from Symfony 6.3

- .github/workflows/ci.yaml
> ci: fix variable reference

- DependencyInjection/ScopedContainer.php
- Tests/DependencyInjection/DoctrinePassTest.php
| Fixed tickets | Fixes #945  
> Wrap hasDefinition in ScopedContainer [fixes #945]
