- Resources/doc/configuration.rst
This was missing in the reference. Closes https://github.com/schmittjoh/JMSSerializerBundle/issues/462
> add enable_short_alias in YAML config reference

- DependencyInjection/Compiler/DoctrinePass.php
- DependencyInjection/JMSSerializerExtension.php
Hi,
Adding:
jms_serializer:
metadata:
infer_types_from_doctrine_metadata: false
Was not working because of the test in JMSSerializerExtension.php. To make the DoctrinePass work, it has to test if the parameter is set, and if the value is set to false. 
Thanks
> Fix jms_serializer.infer_types_from_doctrine_metadata usage

- DependencyInjection/Compiler/RegisterEventListenersAndSubscribersPass.php
Was `listener` instead of `subscriber`.
> Fix bad Tag name in error message

- Resources/config/services.xml
Visitors take only one parameter in the constructor (the naming strategy).
> Remove unused params in visitors

- ContextFactory/ConfiguredContextFactory.php
- DependencyInjection/Configuration.php
- DependencyInjection/JMSSerializerExtension.php
- Resources/config/services.xml
- Tests/ContextFactory/ConfiguredContextFactoryTest.php
- Tests/DependencyInjection/ConfigurationTest.php
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
- Tests/ExpressionLanguage/ExpressionLanguageTest.php
This PR adds functionality for setting up default context parameters for serializer via configuration:
```yaml
jms_serializer:
default_context:
serialization:
serialize_null: false
version: ~ 
attributes: {}
groups: ['Default']
deserialization:
serialize_null: false
version: ~ 
attributes: {}
groups: ['Default']
```
Also this PR fixes deprecation warnings in tests.
> Added configuration for default context

- Resources/config/services.xml
I ran into issue #397 which can be solved without adding a new strategy class (as suggested in the issue) by using `SerializedNameAnnotationStrategy` with `IdenticalPropertyNamingStrategy` as delegate:
``` yml
services:
my_custom_naming_strategy:
class: %jms_serializer.serialized_name_annotation_strategy.class%
public: false
arguments:
- @jms_serializer.identical_property_naming_strategy
jms_serializer.naming_strategy:
alias: my_custom_naming_strategy
```
However the bundle does not define the `IdenticalPropertyNamingStrategy` as it does with other strategies. This PR adds the definition for a `jms_serializer.identical_property_naming_strategy` service which can be referenced from a custom strategy service definition.
Until this PR is merged, you can add the following (e.g. to your …
> add service definition for IdenticalPropertyNamingStrategy

- Resources/config/services.xml
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
To get rid of
> Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "jms_serializer.serializer" service to "JMS\Serializer\SerializerInterface" instead.
See https://github.com/symfony/symfony/pull/22295 and https://github.com/symfony/symfony/pull/22098
> Allow autowiring serializer

- DependencyInjection/Compiler/TwigExtensionPass.php
- JMSSerializerBundle.php
- Resources/config/services.xml
- Tests/DependencyInjection/TwigExtensionPassTest.php
- composer.json
Fixes https://github.com/schmittjoh/JMSSerializerBundle/issues/562
requires https://github.com/schmittjoh/serializer/pull/747 (probably jms serializer 1.7), twig 1.26 and symfony 3.2
> Added runtime twig extension support (significant performance improvements)

- Resources/config/services.xml
- autowiring aliases should be private, as there is no reason to expose these ids at runtime (autowiring needs them at compile time only)
- autowiring aliases should point to the preferred alias rather than to the actual service, to be compatible with services deciding to decorate the serializer using the preferred alias (which is the id they know)
> Improve the autowiring configuration

- composer.json
`jms/serializer` requires PHP version > 5.5 anyway, so it could be adjusted on bundle as well. Also, as a proposal, I have changed `>=` to `^`, because it is more semantically correct. You cannot prove that this bundle will work with PHP 8.0
> [Composer] Upgrade required php version

- .travis.yml
- Tests/ContextFactory/ConfiguredContextFactoryTest.php
- Tests/DependencyInjection/ConfigurationTest.php
- Tests/DependencyInjection/CustomHandlerPassTest.php
- Tests/DependencyInjection/DoctrinePassTest.php
- Tests/DependencyInjection/EventSubscribersAndListenersPassTest.php
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
- Tests/DependencyInjection/NamingStrategyTest.php
- Tests/DependencyInjection/TwigExtensionPassTest.php
- Tests/ExpressionLanguage/ExpressionLanguageTest.php
- composer.json
In FOSRestBundle, we need this to test for compatibility with Symfony 4 (see FriendsOfSymfony/FOSRestBundle#1708).
> compatibility with Symfony 4

- DependencyInjection/Compiler/RegisterEventListenersAndSubscribersPass.php
- Tests/DependencyInjection/EventSubscribersAndListenersPassTest.php
- Tests/DependencyInjection/Fixture/SimpleHandler.php
Fixes https://github.com/schmittjoh/JMSSerializerBundle/issues/593
> Allow listeners and event subscribers to be private

- Resources/config/services.xml
- Tests/DependencyInjection/CustomHandlerPassTest.php
- Tests/DependencyInjection/DoctrinePassTest.php
- Tests/DependencyInjection/EventSubscribersAndListenersPassTest.php
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
- Tests/DependencyInjection/NamingStrategyTest.php
- Tests/DependencyInjection/TwigExtensionPassTest.php
- composer.json
(and improve test cases by using always all default symfony compiler passes)
This is the first step for a better support for symfony 4.0
> Remove dependencies from translator and form handler

- DependencyInjection/Compiler/FormErrorHandlerTranslationDomainPass.php
- JMSSerializerBundle.php
- Tests/DependencyInjection/FormErrorHandlerTranslationDomainPassTest.php
Injected translation domain parameter (validator.translation_domain) to FormErrorHandler. This is a solution suggestion for the following issue: https://github.com/schmittjoh/JMSSerializerBundle/issues/501 and https://github.com/schmittjoh/serializer/pull/783
> Injected validator.translation_domain to FormErrorHandler

- DependencyInjection/Compiler/CustomHandlersPass.php
- DependencyInjection/Compiler/DoctrinePass.php
- DependencyInjection/Compiler/RegisterEventListenersAndSubscribersPass.php
- DependencyInjection/Compiler/TwigExtensionPass.php
If another part of the application decorates a built-in service, the
compiler passes will fail if they run after service decorators have
been resolved (in this case, the original service id is an alias
pointing to the decorating service).
> make it possible to decorate services

- DependencyInjection/Compiler/CustomHandlersPass.php
- DependencyInjection/Compiler/RegisterEventListenersAndSubscribersPass.php
- composer.json
requires schmittjoh/serializer#844
> support lazily loaded event listeners and handlers

- DependencyInjection/Compiler/CustomHandlersPass.php
There was a conflict between #618 and #620 which should be resolved by this change.
> drop getDefinition() in favor of findDefinition()

- Resources/config/services.xml
Since Symfony 3.2, getting private service from the container has been deprecated.
This PR solves issue #632.
> make serializer/deserializer visitor services public

- DependencyInjection/Compiler/CustomHandlersPass.php
- Tests/DependencyInjection/CustomHandlerPassTest.php
- Tests/DependencyInjection/Fixture/UserDefined/UserDefinedSubscribingHandler.php
- composer.json
As a response to #642, #641 and #466 I prepared a proposal of change/feature in this regard, which should improve DX and let developers avoid confusion or similar problems in future.
What these changes introduce:
1. Possibility to give `jms_serializer.handler` and `jms_serializer.subscribing_handler` tags a priority attribute
2. `CustomHandlersPass` is loading handlers respecting order based on priorities
3. Standard handlers have a default priority set to `100` (ones from `JMS\Serializer` namespace)
4. Custom defined handlers (outside of namespace above) have a default priority set to `0` (will override standard ones by default)
> Proposal: Add priorities feature to handlers

- DependencyInjection/Compiler/CustomHandlersPass.php
- Tests/DependencyInjection/CustomHandlerPassTest.php
This fixes #656 by examining the priorities for each direction+type+format combination and not globally.
This now allows to register the same handler for multiple types and/or formats as it was possible in pre 2.4 versions.
> Fix serialization handler registration by priority

- DependencyInjection/JMSSerializerExtension.php
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
Same as #670 but for 2.x 
So basically only with the `registerForAutoconfiguration` checks.
> Add autoconfigure for handlers

- Resources/config/services.xml
Fixes https://github.com/schmittjoh/JMSSerializerBundle/issues/690
handlers and event listeners are managed by lazy-handler-registry  and lazy-event-handler
> remove lazy services, they are already lazy in many contexts

- DependencyInjection/Compiler/RegisterEventListenersAndSubscribersPass.php
- Tests/DependencyInjection/EventSubscribersAndListenersPassTest.php
You forgot to adapt CompilerPass for changes in commit below.
https://github.com/schmittjoh/serializer/commit/d0cf4cbca029bf55eb3d4061b3affbe3c2022f2b#diff-f5a58b28905e2b53063b7633beb9e605
> EventDispatcher - use case sensitive event names;

- Resources/config/services.xml
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
|Q            |A     |
|---          |---   |
|Branch       |master|
|Bug fix?     |no    |
|New feature? |no    |
|BC breaks?   |no    |
|Deprecations?|no    |
|Tests pass?  |yes   |
|Fixed tickets|n/a   |
|License      |MIT   |
|Doc PR       |n/a   |
> Add service aliases in order to enable autowiring for "configured_serialization_context_factory" and "configured_deserialization_context_factory"

- DependencyInjection/JMSSerializerExtension.php
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
|Q            |A     |
|---          |---   |
|Branch       |master|
|Bug fix?     |yes   |
|New feature? |no    |
|BC breaks?   |no    |
|Deprecations?|no    |
|Tests pass?  |yes   |
|Fixed tickets|n/a   |
|License      |MIT   |
|Doc PR       |n/a   |
Without these changes, configuring the serializer with the following definition is not possible.
```yaml
jms_serializer:
visitors:
json_serialization:
options: 0 # json_encode options bitmask, suggested JSON_PRETTY_PRINT in development
```
> Allow to call `JsonSerializationVisitorFactory::setOptions()` with value `0`

- Resources/doc/configuration.rst
I was confused by the comment, as `JSON_PRETTY_PRINT` only makes sense for JSON serialization. After looking at the code, I don't see the deserialization visitor executing `json_encode()` anywhere. I propose to slightly modify the comment for `json_deserialization`
> [doc] Removed confusing JSON_PRETTY_PRINT suggestion from json_deserialization

- DependencyInjection/Compiler/DoctrinePass.php
- DependencyInjection/JMSSerializerExtension.php
- Resources/config/services.xml
- Tests/DependencyInjection/DoctrinePassTest.php
- composer.json
Use symfony decorators to decorate metadata drivers and object constructors.
This simplifies a lot the code and makes possible a better decoration process. the previous implementation was self-implementing the decoration process
> Use symfony decorators

- Cache/CacheClearer.php
- Resources/config/services.xml
- Tests/Cache/CacheClearerTest.php
- composer.json
| Fixed tickets | #834 
Works only with https://github.com/schmittjoh/metadata/pull/97
> add CacheClearer

- DependencyInjection/JMSSerializerExtension.php
- Tests/DependencyInjection/ConfigurationTest.php
| Fixed tickets | https://github.com/schmittjoh/JMSSerializerBundle/pull/839#discussion_r613792671
This is a follow up fix for the issue brought up in the cache clearer comment.
> Remove cache clearer service when cache is disabled

- .phpcs.xml.dist
- DependencyInjection/Compiler/CustomHandlersPass.php
- DependencyInjection/Compiler/DoctrinePass.php
- DependencyInjection/Compiler/ExpressionFunctionProviderPass.php
- DependencyInjection/Compiler/FormErrorHandlerTranslationDomainPass.php
- DependencyInjection/Compiler/RegisterEventListenersAndSubscribersPass.php
- DependencyInjection/Compiler/ServiceMapPass.php
- DependencyInjection/Compiler/TwigExtensionPass.php
- DependencyInjection/JMSSerializerExtension.php
- JMSSerializerBundle.php
- Resources/config/services.xml
- Tests/DependencyInjection/ConfigurationTest.php
- Tests/DependencyInjection/CustomHandlerPassTest.php
- Tests/DependencyInjection/EventSubscribersAndListenersPassTest.php
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
- composer.json
| BC breaks?    | yes
| Fixed tickets | -
> Allow to decorate handler registry and event dispatcher

- Resources/doc/installation.rst
| Doc updated   | yes
| Tests pass?   | N/A
| Fixed tickets | partially #865
The install guide only shows information for older "Symfony Standard Edition" applications.  This adds info for Flex-based applications.
> Update installation guide to include Flex based apps

- Cache/CacheWarmer.php
- DependencyInjection/JMSSerializerExtension.php
- ExpressionLanguage/BasicSerializerFunctionsProvider.php
Adds a couple of doc blocks to silence Symfony's `DebugClassLoader` when run on Symfony 5.4+
> Add doc blocks to silence Symfony deprecations

- JMSSerializerBundle.php
When `TwigBundle` is added before `JMSSerializerBundle` in `bundles.php` the following errors occurs:
```
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
The service "twig" has a dependency on a non-existent service "jms_serializer.twig_extension.serializer". Did you mean one of these: "jms_serializer.twig_ext
ension.runtime_serializer", "jms_serializer.twig_extension.serializer_runtime_helper"?
```
This is happening because the `TwigEnvironmentPass` finds all services tagged with `twig.extension`.
Then the `TwigExtensionPass` of JMSSerializerBundle removes the extension. This leaves `twig` service
with a reference to an unknown service.
> Run `TwigExtensionPass` with higher priority

- Resources/views/Collector/panel.html.twig
| Tests pass?   | no
| Fixed tickets | #... 
This PR fixes a minor alignment issue in the dev toolbar
Before:
After:
> Fixed dev toolbar styling issue

- Debug/DataCollector.php
Had not been changed after PR#900 replaced TraceableDriver with TraceableMetadataFactory
| Tests pass?   | yes?
| Fixed tickets | #902 
> Fix: update class and property name of metadata service in DataCollector

- Debug/TraceableFileLocator.php
- DependencyInjection/JMSSerializerExtension.php
- Resources/config/debug.xml
- Resources/views/Collector/metadata.html.twig
- Tests/DependencyInjection/ConfigurationTest.php
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
| Fixed tickets | #858
The `TraceableFileLocator`, which was introduced in #858, to log some data for Symfony's profiler panel, was broken. It implemented a method that doesn't exist anywhere in the project and thus never gets called, so nothing is logged. In the profiler panel you may think everything's alright, though, as the message `if this list is empty, probably all the data are cached as expected` gets displayed, which is probably even true most of the time.
The new `TraceableFileLocator` now also decorates the original one, instead of extending it, which makes it more flexible in case …
> Fix `TraceableFileLocator`

- UPGRADING.md
| Doc updated   | yes
The configuration by parameters is no longer available. This was missing in the UPGRADING.md
> Add migration for naming strategy by parameters from 2.x to 3.x

- DependencyInjection/JMSSerializerExtension.php
- Resources/config/services.xml
Right now, without adding a compiler pass in a downstream application, the metadata drivers can't receive an expression evaluator.  This adds support for injecting the configured evaluator as long as the service implements `JMS\Serializer\Expression\CompilableExpressionEvaluatorInterface`.
> Add support for injecting the expression evaluator into metadata drivers

- DependencyInjection/JMSSerializerExtension.php
- Tests/DependencyInjection/ConfigurationTest.php
- Tests/DependencyInjection/CustomHandlerPassTest.php
- Tests/DependencyInjection/DoctrinePassTest.php
- Tests/DependencyInjection/EventSubscribersAndListenersPassTest.php
- Tests/DependencyInjection/FormErrorHandlerTranslationDomainPassTest.php
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
- Tests/DependencyInjection/NamingStrategyTest.php
- Tests/DependencyInjection/TwigExtensionPassTest.php
| BC breaks?    | depends
| Tests pass?   | yes/no
| Fixed tickets | #...
Symfony changed its "Directory Structure Best Practice for Reusable Bundles" in its 4.4 version.
In the old one, everything was just in the bundle root dir `/` (or maybe inside `/src`, in which case this was considered "root").
In the new one, the PHP classes moved inside `/src` and the contents of `/Resources` are unpacked into the root `/` (with sometimes different names).
Below is a comparison of the old and the new structure:
<table>
<thead align="center">
<td><a href="https://symfony.com/doc/4.3/bundles/best_practices.html#directory-structure">Symfony < …
> Support modern bundle structure

- DependencyInjection/Compiler/CustomHandlersPass.php
- Tests/DependencyInjection/CustomHandlerPassTest.php
This is a bit of a micro-optimization but should get rid of a small performance penalty when first instantiating the serializer and its services.
As part of creating the serializer service, the handler registry is initialized as well.  For the production environment, that registry is generally an instance of `JMS\Serializer\Handler\LazyHandlerRegistry` unless someone's been messing with the container with their own passes or service overrides.  That class supports having a handlers array injected into its constructor which can allow a caller to pre-build the internal registry …
> Optimize injecting the handlers to the registry when the handler registry is a lazy registry

- Debug/DataCollector.php
- DependencyInjection/Compiler/AdjustDecorationPass.php
- DependencyInjection/Compiler/PerInstancePass.php
- DependencyInjection/JMSSerializerExtension.php
- JMSSerializerBundle.php
Symfony 6.3 added a number of return types to the framework.  This PR should cover all the ones that popped up when beta testing an application.
Native types are used in all final/internal classes, doc block annotation used otherwise.
> Add return types to silence Symfony 6.3 deprecation notices

- DependencyInjection/JMSSerializerExtension.php
- Resources/config/services.xml
| Fixed tickets | #931
Fixes the reported issue with a hacky workaround of not wiring in the attribute driver.  I've hit too many brick walls trying to make the annotations/attributes drivers support null returns (decorating drivers expect non-null returns, hierarchical stuff breaks without a metadata object being returned), so until everything can be made to work correctly without these drivers always creating a metadata object, this is the quickest solution.
> Don't wire the AttributeDriver

- Templating/SerializerHelper.php
| Deprecations? | yes
In https://github.com/symfony/symfony/pull/51144 the `symfony/templating` component is deprecated for the 6.4 release and removed for 7.0.  This deprecates the integration from this bundle.
> Deprecate the templating component integration

- .github/workflows/ci.yaml
- .phpcs.xml.dist
- Cache/CacheWarmer.php
- DependencyInjection/Configuration.php
- DependencyInjection/JMSSerializerExtension.php
- ExpressionLanguage/BasicSerializerFunctionsProvider.php
- Tests/DependencyInjection/ConfigurationTest.php
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
- composer.json
| BC breaks?    | technically yes
Adds Symfony 7 support, WIP as this builds on top of #933 to ensure it works with the annotations support being removed.
Since the first push of this PR failed on the lowest deps build because of incompatible signatures, this will also drop support for Symfony versions before 5.4 (current LTS), and bumps the PHP minimum to 7.4 because according to the [Packagist stats](https://packagist.org/packages/jms/serializer-bundle/php-stats#5) the number of folks running a 5.x release of the bundle on PHP 7.2 or 7.3 is so insignificant that at this point it's just more …
> Add support for Symfony 7, require Symfony 5.4+ and PHP 7.4+

- .phpcs.xml.dist
- Cache/CacheClearer.php
- Cache/CacheWarmer.php
- ContextFactory/ConfiguredContextFactory.php
- DependencyInjection/Compiler/AssignVisitorsPass.php
- DependencyInjection/Compiler/CustomHandlersPass.php
- DependencyInjection/Compiler/DoctrinePass.php
- DependencyInjection/Compiler/ExpressionFunctionProviderPass.php
- DependencyInjection/Compiler/FormErrorHandlerTranslationDomainPass.php
- DependencyInjection/Compiler/PerInstancePass.php
- DependencyInjection/Compiler/RegisterEventListenersAndSubscribersPass.php
- DependencyInjection/Compiler/TwigExtensionPass.php
- DependencyInjection/Configuration.php
- DependencyInjection/DIUtils.php
- DependencyInjection/JMSSerializerExtension.php
- ExpressionLanguage/BasicSerializerFunctionsProvider.php
- Serializer/StopwatchEventSubscriber.php
- Templating/SerializerHelper.php
- Tests/DependencyInjection/Fixture/AnotherSimpleObject.php
- Tests/DependencyInjection/Fixture/DefaultValuePropObject.php
- Tests/DependencyInjection/Fixture/IncludeInterfaces/AnInterfaceImplementation.php
- Tests/DependencyInjection/Fixture/IncludeInterfaces/AnObject.php
- Tests/DependencyInjection/Fixture/ObjectUsingEnumDeserialize.php
- Tests/DependencyInjection/Fixture/ObjectUsingExpressionLanguage.php
- Tests/DependencyInjection/Fixture/ObjectUsingExpressionProperties.php
- Tests/DependencyInjection/Fixture/VersionedObject.php
- Tests/DependencyInjection/JMSSerializerExtensionTest.php
- Tests/DependencyInjection/TwigExtensionPassTest.php
- composer.json
Basic coding standards package update, then `phpcbf` run to apply modifications post-update.
> Bump `doctrine/coding-standard` to latest

- Debug/DataCollector.php
Subj.
See also: https://wiki.php.net/rfc/deprecate-implicitly-nullable-types
| Fixed tickets | nope
> Fix PHP 8.4 deprecation notice
